### ISSUE TITLE
HaXml missing from Stackage

### ISSUE THREAD

**Issue by FranklinChen** [hackage-trustees/malcolm-wallace-universe#2]
Is there a reason HaXml is not in Stackage? https://www.stackage.org/

I think it would be useful for it to be in there.

**Comment by cartazio** [comment]
Our remit is hackage not stackage.  

Also there are structural issues with how stackage works that are at direct conflict with our responsibilities.

**Comment by gbaz** [comment]
To clarify a bit further: package maintainers or people who wish to volunteer in their stead can add packages to stackage through the stackage process. This repo was just created as an intermediate tool for hackage trustees to perform non-maintainer-updates for hackage. Certainly packages can be added to stackage, but this repo and the trustee team aren't relevant to that process :-)
